name: Bug report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Provide a more detailed introduction to the issue itself,
        and why you consider it to be a bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Tell us what you expected would happen.
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: Tell us what happens instead.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: >-
        Provide a link to a live example, or an unambiguous set of steps to
        reliably reproduce the bug. Include a link to a savefile that exhibits
        the error, if relevant. Remember to also list any mods you are using.
      placeholder: |
        1.
        2.
        3.
        4.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: How has this bug affected you? What were you trying to accomplish?
    validations:
      required: false
  - type: textarea
    id: fix
    attributes:
      label: Possible fix
      description: >-
        Not obligatory, but if you have an idea for how to fix the bug,
        you can suggest it here. Or if you're planning to fix it yourself in
        a pull request.
    validations:
      required: false
  - type: input
    id: mod_version
    attributes:
      label: Mod version
      description: The version of Cybersyn Combinator that you're using.
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: factorio_version
    attributes:
      label: Factorio version
      description: The version of Factorio that you're using.
      placeholder: '1.1.76'
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: The operating system (and preferably version) that you're using.
      placeholder: ex. Windows 10 x64 Version 1607 OS Build 14339.693
    validations:
      required: true
